name: test_timer
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.0.3
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  rxdart: ^0.27.4
  stop_watch_timer: ^1.5.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
